apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: iscatalogue
  description: The team responsible for Catalogue
spec:
  type: team
  profile:
    displayName: IS Catalogue
    email: catalogue@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: engineering
  children: [backstage, other]
  members: [gurmeet00007, john123]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: The Engineering business unit
spec:
  type: team
  children: [iscatalogue]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: leadership
  description: The leaderthip team
spec:
  type: team
  parent: engineering
  children: []
  members: [john123]
